name: Java CI with Maven

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-war
          path: target/*.war
